### PR TITLE
Feature/authentication strategies

### PR DESCRIPTION
**Pull request by shtelzerartem**
### Issue
Current bitbucket lib is not supporting authorization strategies for OAuth. 

### What I have done? 
I have implemented main OAuth2 authorization methods to retrieve ```access_token```. 
It's a draft pull request for bitbucket authStrategies. Would be happy if someone will check or test it. 

- [x] Authorization Code Grant 
- [ ] Implicit Grant
- [x] Resource Owner Password Credentials Grant
- [x] Client Credentials Grant
- [x] Bitbucket Cloud JWT Grant (urn:bitbucket:oauth2:jwt)

https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication

Related issue #18

### CODE REVIEW

**Comment by MunifTanjim** [comment]
Hey @shtelzerartem , thanks for openning this draft.

I see there are many unrelated changes. It would make reviewing this so much harder. For example:

- gitignore
- updating package versions, changing build script, adding other scripts in package.json
- Changing names for types and variables.

Can you please remove those?

**Comment by shtelzerartem** [comment]
@MunifTanjim yes, for sure! 
I still feel a bit frustrated about the structure of auth plugin and its flow. 
That is why I have done a draft PR: just to describe the general idea of the organization of authentication strategies. 
Also, there are some other things that are missing right now, for example, after hook to refresh ```access_token``` if it is expired.

I will probably clean the code soon, so you will be able to review it.

**Comment by shtelzerartem** [comment]
@MunifTanjim hey, I have tried to clear it as much as possible. 
There are structural changes, I merged together auth and authentication plugins into one monolith plugin for the first solution. I need your help with splitting them, as it was done in github's octokit.

**Comment by Raspikabek** [comment]
It might be the case I'm implementing it wrong, but I'm getting an error when trying to test this.

What I've done so far:

* cloned @shtelzerartem  repository & checked out to feature/authentication-strategies branch
* executed `yarn` & `yarn pack`
* created a test script and implementing the method in the following form:

```
import { Bitbucket } from './lib/index.js'

const doSomething = async () => {
  const options = {
    authStrategy: 'OAuth',
    auth: {
      grant_type: 'clientCredentialsGrant',
      client_id: 'OAUTH_CONSUMER_CLIENTID',
      client_secret: 'OAUTH_CONSUMER_SECRET'
    }
  }
  try {
    const bitbucket = new Bitbucket(options)
    console.log(await bitbucket.auth())
    const result = await bitbucket.user.get({})
    console.log(result)
  } catch (err) {
    console.error(err)
  }
}

doSomething()

```

This returns the following error:

```
TypeError: Cannot read property 'defaults' of undefined
    at N (~/node-bitbucket/lib/index.js:1:12882)
    at J (~/node-bitbucket/lib/index.js:1:13336)
    at ~/node-bitbucket/lib/index.js:1:13675
    at ~/node-bitbucket/lib/index.js:1:13605
    at ~/node-bitbucket/lib/index.js:1:13641
    at ~/node-bitbucket/lib/index.js:1:13511
    at ~/node-bitbucket/lib/index.js:1:14210
    at ~/node-bitbucket/lib/index.js:1:14078
    at ~/node-bitbucket/lib/index.js:1:14112
    at ~/node-bitbucket/lib/index.js:1:13984
```

If I change the auth method to use an AppPassword does return my account information accordingly.

Wonder if there's something wrong in the test script or I'm missing something right now. I guess the expected result is to start the authentication process. I wonder if there's any specific callback URL we should use like HTTPs://localhost:1234/oauth2  or whatsoever in the setup of the bitbucket OAuth consumer application.

Thanks and great job! I'm really keen to see this working and report any issues. (don't have the skill-set right now to contribute in the development side)

**Comment by shtelzerartem** [comment]
@Raspikabek hey, thanks for testing! Yep, there was a bug, that I have fixed in the latest commit. 
About implementation — everything is right.

**Comment by Raspikabek** [comment]
> @Raspikabek hey, thanks for testing! Yep, there was a bug, that I have fixed in the latest commit.
> About implementation — everything is right.
> 
> About callbacks. Are you talking about `Authorization Code Grant` and `Implicit grant` authentication methods, where the user has to be redirected to bitbucket and then returned back with token params in the query? If yes, unfortunately, I haven't been working on this part.

Nice! Now seems to be working! Thanks for the quick response.

Related to `Implicit grant` & `Authorization Code Grant` I guess that might require to implement and import an `express` application of some sort to include it in the package.

BTW `Authorization Code Grant` even though I've added a code, it does return an error:

```
  error: {
    error_description: 'Missing required field: code',
    error: 'invalid_request'
  },
  ```

Anyway... I guess the best approach to implement a secure login process using this library would be by using the JWT Auth and implementing the authorization process to get the JWT token from my own application (the one that requires this library) using something like [this example](https://bitbucket.org/atlassian/bb-cloud-jwt-grant-sample-app/src/master/) provided by Atlassian

Again thanks a million for the hard work!

**Comment by shtelzerartem** [comment]
@Raspikabek thank you for another one bug! I will fix it soon. 

About ```Implicit grant``` and ```Authorization Code Grant``` (all the ```https://bitbucket.org/site/oauth2/authorize``` requests). This library must not provide a way to resolve them, but just allow you to authenticate requests having responses from them. 

**Implicit grant** 
After redirect to your service you will be able to pull out from URL ```#access_token={token}&token_type=bearer``` access_token and him as option to Bitbucket Object.

```javascript
new Bitbucket({
  auth: {
    type: 'token',
    token: '<YOUR BEARER TOKEN>',
  },
})
```

**Authorization Code Grant**
From ```https://bitbucket.org/site/oauth2/authorize?client_id={client_id}&response_type=code``` you will be redirected to URL with ```?code={code}```, which you will be able to use further.

```javascript
new Bitbucket({
  authStrategy: 'OAuth',
  auth: {
    grant_type: 'authorizationCodeGrant',
    client_id: '<CLIENT ID>',
    client_secret: '<CLIENT SECRET>',
    code: '<CLIENT CODE>',
  },
})
```

With JWT Auth I think, the same trick.

**Comment by shtelzerartem** [comment]
@MunifTanjim have you had a chance to go over, it looks, like everything we went over with @Raspikabek work fine.

File: src/endpoint/types.ts [hunk 1]
```diff
@@ -43,7 +43,7 @@ export interface Endpoint {
   DEFAULTS: EndpointDefaults
   defaults(endpointOptions: EndpointParams): Endpoint
   merge(
-    endpointRoute: string,
+    endpointRoute: string | EndpointOptions,
```
Comment (MunifTanjim) [inline src/endpoint/types.ts:46]: This doesn't seem right. Why was it changed? 🤔

File: src/index.ts [hunk 2]
```diff
@@ -8,11 +8,11 @@ import validateRequestPlugin from './plugins/validate-request'
 
 const Plugins = [
   noticePlugin,
-  authPlugin,
   paginationPlugin,
   registerEndpointsPlugin,
   registerApiEndpointsPlugin,
   validateRequestPlugin,
+  authPlugin,
```
Comment (MunifTanjim) [inline src/index.ts:15]: Any particular reason for changing the order?

File: package.json [hunk 3]
```diff
@@ -29,7 +29,7 @@
     "build:core": "bili",
     "prebuild:plugins": "rimraf lib/plugins/*.js lib/plugins/*.js.map",
     "build:plugins": "npm-run-all -s build:plugin:*",
-    "build:plugin:authenticate": "PLUGIN=authenticate bili",
+    "build:plugin:auth": "cross-env PLUGIN=auth bili",
```
Comment (MunifTanjim) [inline package.json:32]: `auth` plugin gets built into the final bundle anyway. Why does it need to be built separately?

File: src/plugins/authenticate/index.ts [hunk 4]
```diff
@@ -1,20 +0,0 @@
...
-  const state: AuthenticatePluginState = {
-    client,
-    auth: undefined,
-  }
-
-  client.authenticate = authenticate.bind(null, state)
-  client.requestHook.before(beforeRequest.bind(null, state))
-}
-
-export default authenticatePlugin
```
Comment (MunifTanjim) [inline src/plugins/authenticate/index.ts:20]: How is removing this plugin related to this PR?

File: src/plugins/auth/OAuth/hook.ts [hunk 5]
```diff
@@ -0,0 +1,15 @@
+import { auth } from './auth'
+
+type AuthState = import('./types').AuthPluginState
+type RequestOptions = import('./types').RequestOptions
```
Comment (MunifTanjim) [inline src/plugins/auth/OAuth/hook.ts:4]: This is not really exported from the `./types` file. I'm facing build error:

```sh
Stack Trace:
Error: /Users/shaikat/Dev/github/MunifTanjim/node-bitbucket/src/plugins/auth/OAuth/hook.ts(4,41): semantic error TS2694: Namespace '"/Users/shaikat/Dev/github/MunifTanjim/node-bitbucket/src/plugins/auth/OAuth/types"' has no exported member 'RequestOptions'.
    at error (/Users/shaikat/Dev/github/MunifTanjim/node-bitbucket/node_modules/rollup/dist/rollup.js:9435:30)
    at throwPluginError (/Users/shaikat/Dev/github/MunifTanjim/node-bitbucket/node_modules/rollup/dist/rollup.js:15754:12)
```

File: src/index.ts (hunk 2 above)
Comment (shtelzerartem) [reply src/index.ts:15]: I will move it back in the next commit.

File: package.json (hunk 3 above)
Comment (shtelzerartem) [reply package.json:32]: I removed it for now as a first solution, and also asked for an [advice on how to do it better](https://github.com/MunifTanjim/node-bitbucket/pull/78#issuecomment-787420622).

Comment (shtelzerartem) [reply package.json:32]: I removed it for now.

File: src/plugins/authenticate/index.ts (hunk 4 above)
Comment (shtelzerartem) [reply src/plugins/authenticate/index.ts:20]: I don't think there is a need for authenticate, I moved it's logic to ```auth/basicAuth```.

File: src/plugins/auth/OAuth/hook.ts (hunk 5 above)
Comment (shtelzerartem) [reply src/plugins/auth/OAuth/hook.ts:4]: Will be fixed in the next commit

File: src/endpoint/types.ts (hunk 1 above)
Comment (shtelzerartem) [reply src/endpoint/types.ts:46]: Yeah, unnecessary change, thanks.

File: src/plugins/authenticate/index.ts (hunk 4 above)
Comment (MunifTanjim) [reply src/plugins/authenticate/index.ts:20]: This is an optional plugin that is not included in the bundle by default. This is here for legacy reason. If we want to remove it, we should put a deprecation notice first.

Bitbucket's API specificaiton is troublesome enough, that introduces breaking changes frequently. I just don't want to add more to it from this library.

Eitherway, this removing this is not related to this PR at all. "If" we want to do this, this should be done in a separate PR.

Comment (shtelzerartem) [reply src/plugins/authenticate/index.ts:20]: Ok, sounds reasonable!

**Comment by shtelzerartem** [comment]
@MunifTanjim any update on this?
